name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
    - # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Full Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.full
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          robonet/dotnet-scratch:full-latest
          robonet/dotnet-scratch:full-6.0
          robonet/dotnet-scratch:full-6.0.12
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          robonet/dotnet-scratch:latest
          robonet/dotnet-scratch:6.0
          robonet/dotnet-scratch:6.0.12
    - name: Minimal Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.minimal
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          robonet/dotnet-scratch:minimal-latest
          robonet/dotnet-scratch:minimal-6.0
          robonet/dotnet-scratch:minimal-6.0.12

