name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
    - # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push runtime-deps
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        target: runtime-deps
        tags: |
          robonet/dotnet-scratch:runtime-deps-latest
          robonet/dotnet-scratch:runtime-deps-7.0
          robonet/dotnet-scratch:runtime-deps-7.0.2
    - name: Build and push runtime-deps-globalization
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        target: runtime-deps-globalization
        tags: |
          robonet/dotnet-scratch:runtime-deps-globalization-latest
          robonet/dotnet-scratch:runtime-deps-globalization-7.0
          robonet/dotnet-scratch:runtime-deps-globalization-7.0.2
    - name: Build and push aspnet
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        target: aspnet
        tags: |
          robonet/dotnet-scratch:aspnet-latest
          robonet/dotnet-scratch:aspnet-7.0
          robonet/dotnet-scratch:aspnet-7.0.2
    - name: Build and push aspnet-globalization
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        target: aspnet-globalization
        tags: |
          robonet/dotnet-scratch:aspnet-globalization-latest
          robonet/dotnet-scratch:aspnet-globalization-7.0
          robonet/dotnet-scratch:aspnet-globalization-7.0.2